### ISSUE TITLE
Typo or on purpose

### ISSUE THREAD

**Issue by steven12138** [daeunni/BECoTTA#1]
## Based on your code, your backbone should be SegFormer, Is this a typo, or i didn't get it right? 

![image](https://github.com/daeunni/BECoTTA/assets/25414059/6ff26326-1b76-4762-9001-829b163a9b02)

**Comment by daeunni** [comment]
Hi, @steven12138. Thanks for your interest. 

Yes, you are right. We utilized Segformer B2/B5 mainly for our experiments. 
However, Segformer mainly adopts a hierarchically structured ViT encoder for its architecture. Therefore, we also utilize the backbone from here (`mmseg/models/backbones/mix_transformer.py`) following the mmsegmentation. 

Also, our MoDE layer can be attached freely to other ViT-based backbones. 

If you have more questions, feel free to ask me. Thanks!

**Comment by steven12138** [comment]
Thank you for the information. I'm also curious, is there a specific reason for choosing Segformer-B2 for the CDS-hard and CGS experiments? or showing the computational efficiency

**Comment by daeunni** [comment]
We just adopt Segformer-B2 for the usefulness of experiments. (Segformer-B2 has the lower parameters than B5, therefore we could conduct quick experiments.) 

However, we verified our method with Segformer B5 on CDS-Easy scenario for the fair comparison with CoTTA paper. 

Therefore, we believe the choose of Segformer version is just a choice for experimental setup. :-)
