### ISSUE TITLE
About the experiment on deeplab

### ISSUE THREAD

**Issue by GennyS** [daeunni/BECoTTA#2]
Hello, can I use deeplab model in mmseg library to run BECoTTA with model pretrained? I may not be familiar with mmseg.

**Comment by daeunni** [comment]
Hi, thanks for your interest. 
Our BECoTTA is mainly based on the Segformer (ViT-based) model, so it was not tested on the deeplab-based model. 
But, I think our BECoTTA consists of plug-and-play layer so you can attach it on the deeplab block with some modification of our MoDE layer and mmseg codes.

**Comment by daeunni** [comment]
If you have any further question, please don't hesitate to reopen the issue. Thanks. :)
