### ISSUE TITLE
Request about your warmup checkpoint release.

### ISSUE THREAD

**Issue by TyroneLi** [daeunni/BECoTTA#3]
Can you release your warmup checkpoint model about B5, since the checkpoint inside backbone seems wrongly initialize the training model, suffering lots of unmatching keys.

**Comment by daeunni** [comment]
Hi, thanks for your interest!
I will upload our checkpoint model asap after the rebuttal period. Thanks a lot.

**Comment by daeunni** [comment]
I just uploaded our checkpoint [here](https://drive.google.com/drive/folders/1iAAjIQ6593b9tDZwsLE1lKO5_3cdRZk2). Thanks for your patience. 
Please refer to [this part](https://github.com/daeunni/BECoTTA#2-flexibility-of-becotta) to implement correctly per each model. Thanks a lot!
