### ISSUE TITLE
Question about offline data generation for WAD phase.

### ISSUE THREAD

**Issue by TyroneLi** [daeunni/BECoTTA#4]
Hi,

I wonder how you generated the foggy style offline images on Cityscapes based on the paper: TSIT???

I notice that TSIT cannot generate the foggy style images.

Could u give some more details about this part? Thanks

**Comment by TyroneLi** [comment]
> Hi,
> 
> I wonder how you generated the foggy style offline images on Cityscapes based on the paper: TSIT???
> 
> I notice that TSIT cannot generate the foggy style images.
> 
> Could u give some more details about this part? Thanks

Hey, could u provide some cues?

**Comment by daeunni** [comment]
Hi, sorry for the late reply. 
You can easily get the foggy Cityscapes dataset [here](https://team.inria.fr/rits/computer-vision/weather-augment/). 
Our WAD is tested using the above fog_transmittance rendering. 

Btw, our BECoTTA has been revised these days, we will release our updated version soon. Thanks. :)

**Comment by cht619** [comment]
how to generate the weather augmentation dataset?

**Comment by daeunni** [comment]
@cht619 Hi, you can refer to my above response. Thanks.
