### ISSUE TITLE
Great Work! Suggestion for Comparison or Discussion with more CTTA/TTA Related Work

### ISSUE THREAD

**Issue by BigDreamer11111** [daeunni/BECoTTA#5]
Hi Daeun Lee,

Firstly, I want to commend you on this great work. It is impressive and provides valuable insights.

I would like to suggest expanding the discussion to include comparisons and discussions with more CTTA or TTA related work. This could provide a broader perspective and further highlight the contributions of your work. Importantly, we all hope that the CTTA field can receive more widespread attention.

Thank you for considering this suggestion.

Best regards,  
Jason

**Comment by daeunni** [comment]
Hi, Jason, 
Thanks for your interest :)
We just finished our ICML camera-ready version (it will be released soon), but we are definitely interested in developing our work. BTW, we already compared some CTTA/TTA works in our paper, so could you elaborate your discussion more? thanks!

**Comment by BigDreamer11111** [comment]
https://github.com/tim-learn/awesome-test-time-adaptation/blob/main/TTA-OTTA.md

Maybe you could search for 'segmentation' or 'continual' in this repo and find some recently published papers to compare.

**Comment by daeunni** [comment]
Thanks for your recommendation. We will consider other works also. Thanks!
